apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-cache-pvc
  namespace: vllm
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi # must be the <=PV capacity
