{{- if and .Values.huggingface.tokenSecretEnabled (not .Values.huggingface.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm.fullname" . }}-hf-token
  namespace: {{ .Release.Namespace }}
  lables:
    {{- include "vllm.labels" . | nindent 4 -}}
type: Opaque
stringData:
  {{ .Values.huggingface.existingSecretKey }}: {{required "Set huggingface.token, or point huggingface.existingSecret at a secret you created yourself" .Values.huggingface.token | quote }}
{{- end }}
