apiVersion: v1
kind: Service
metadata:
  name: {{ include "vllm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec: # defaults to type:ClusterIP
  ports:
  - port: 8000 # where the container listens on (same as containerPort in deployment)
    targetPort: 8000 # what the service exposes inside the cluster)
    protocol: TCP
    name: http
  selector:
    {{- include "vllm.selectorLabels" . | nindent 4 }}
